#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/group/neurolab/neuron_python"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/group/neurolab/neuron_python/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/bwjmbb/Software_Tutorials/SW_3/x86_64/.libs/libnrnmech.so" "$@"
